### ISSUE TITLE
Wave Bank cut off screen on 720p screens

### ISSUE THREAD

**Issue by bryc** [squiggythings/WaveTracker#1]
On resolutions like 1360x768 and 1366x768 at 200%, half of the Wave Bank is off screen and cannot be accessed. These resolutions are very common in lower spec laptops.

![image](https://github.com/user-attachments/assets/468853e6-1380-4579-a154-cb40a929dd0e)

It might be cool to have a scroll bar like the channel rack uses!

Though everything else seems to be viable at this resolution.

**Comment by squiggythings** [comment]
This will be fixed in the next patch
