### ISSUE TITLE
[BUG] Sample loop bug

### ISSUE THREAD

**Issue by alex135t** [squiggythings/WaveTracker#13]
**Describe the bug**
When modifing a sample's Loop mode to forward or ping pong. You can change the loop position but it can go in the negatives and clip out the window.

Here is an image of the bug in action:
https://imgur.com/a/h3Qmlkm

**To Reproduce**
1. Load any sample
2. Set the loop mode to either forward or ping pong
3. Set the loop position to a negative number
4. Voila!

**Expected behavior**
I don't think it should clip out of the window

**Desktop (please complete the following information):**
Windows 10

**Comment by squiggythings** [comment]
Thanks for letting me know, it can also be set beyond the end of the sample as well. This will be fixed in an upcoming patch.
