### ISSUE TITLE
[BUG] Incorrect Tick Speed displayed in Module Settings (Isn't getting updated)

### ISSUE THREAD

**Issue by bryc** [squiggythings/WaveTracker#16]
For a song I'm working on, I'm using a 68 hz speed (with speed value of 6) to approximate the target of 167 BPM.

When I launch WaveTracker and load my file, the song appears to correctly play at 68 hz, but when I open Module Settings, it shows "60 hz (Default)". Basically I think the dialog is not properly detecting the custom rate and this might lead users to think their custom rate was not saved.

**Comment by squiggythings** [comment]
Thanks for letting me know, this will be fixed in an upcoming patch.
