### ISSUE TITLE
[BUG] Tremolos seem to turn off after some time looping song, and isn't reset with repeat effect commands

### ISSUE THREAD

**Issue by bryc** [squiggythings/WaveTracker#18]
**Describe the bug**
I have defined two tremolos in frame 0 (`734` and `725`), for constant tremolo effect on the chords throughout a song. After the 3 minute song finishes and then repeats, I've noticed that the first tremolo stops working (noticeable in the visualizer). The second slower tremolo then stops halfway through the second play of the song.

Pressing the play button seems to reset the tremolo, but it does seem to run out of time again.

**To Reproduce**
Put tremolo (`734` and `725`) in frame 0, and play the song on loop, they eventually stop working after 3 minutes.

**Expected behavior**
The tremolo should always be active.

**Comment by squiggythings** [comment]
Thanks for letting me know, turns out this also happens with vibrato effects too. It will be fixed in an upcoming patch.
