### ISSUE TITLE
Importing .FLAC sample breaks typing keyboard sound output

### ISSUE THREAD

**Issue by bryc** [squiggythings/WaveTracker#2]
**Describe the bug**
Playing a Sample instrument using a .FLAC sample causes all other Wave instruments to not play.

**To Reproduce**
1. Open program, for a empty default module.
2. Create new sample instrument, load bd.flac, close instrument editor (X out).
3. Deselect Sample instrument, and Select Wave instrument, then hold Q, sine wave will play.
4. Select Sample instrument, press Q - no sound will play.
5. Select Wave instrument again, hold Q - sine wave will no longer play.

**Expected behavior**
The sine wave should play without issue.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2 (19045.2075)

**Additional info**
* I saved the .FLAC using OpenMPT. 
* The program has to be closed and reopened to fix the issue.

FLAC file here: [bassdrum.zip](https://github.com/user-attachments/files/16826000/bassdrum.zip)

**Comment by squiggythings** [comment]
Looks like NAudio is throwing an exception when loading that specific .flac file unfortunately. For now I think it will be best to ensure that the program handles any such error properly by letting you know the sample failed to load and not letting it stall channel playback.

**Comment by squiggythings** [comment]
These changes are included in the latest patch, will close this issue
