### ISSUE TITLE
[BUG] Resizing window causes pattern editor to scroll wildly

### ISSUE THREAD

**Issue by ajsosa** [squiggythings/WaveTracker#22]
**Describe the bug**
Resizing window causes pattern editor to scroll wildly. Problem area below.

https://github.com/squiggythings/WaveTracker/blob/a4418e79703f3ed04e7e691eb1c492dfadb22a08/Source/UI/PatternEditor.cs#L397
 
What looks to be happening is that clicking the bottom right corner to resize window is triggering the mouse selection mode in the pattern editor. If you purposely `false` that conditional, you can resize without issue. I *THINK* this might be because it's not taking into account the instrument UI element being drawn on top and the size of the pattern editor is extending to main window edge.

**To Reproduce**
Open wave tracker and begin resizing window with mouse using bottom right corner.

**Expected behavior**
Resize window while maintaining pattern editor position.

**Desktop:**
 - OS: Win 10

**Comment by squiggythings** [comment]
Thanks for letting me know, this will be fixed in an upcoming patch.
