### ISSUE TITLE
[Feature Request] Sample editor undo + ideas

### ISSUE THREAD

**Issue by bryc** [squiggythings/WaveTracker#29]
Considering WaveTracker has very useful sample editing tools, I think having an Undo ability would be huge, since one mistake means having to reload the sample and start again. 

And if fleshing it out is on the table (no pressure at all; it's nice that I can even load samples period), a couple of ideas that I feel would really enhance it:

* Selection dragging - a way to resize one side of a selection, either by detecting/highlighting the side closest to mouse cursor, or holding Shift and dragging one side.
* Zooming into sample - incredibly useful for narrowing down exact loop points. Also a vertical zoom (visual amplification only) could provide a ton of insight especially when looking at low volume sections.
* Resampling/downsampling - something I use all the time in sample trackers is downsampling them to get them smaller and more lo-fi sounding, usually halving the rate from 44100 to 22050, or again to 11025. Doing so usually fits the chiptune aesthetic and having a quick way to do this (without having to do it in OpenMPT or some other app) would be awesome.
* Stereo-to-Mono downmixing - Sometimes user might load a kick drum and it might be in stereo (lots of DAWs only export in stereo). Having a quick and easy way to downmix it to mono would be useful if that was the intention.
* Bit-depth reduction - sometimes you also want a sample to be 8-bit or so, which inherently adds a bit of noise or reduces dynamic range in a satisfying way. I know there's an effect that can do this real time, but being able to bake it into the sample would be a plus.
* DC Offset Removal - sometimes a sample or parts of a sample aren't centered, which may affect certain operations, having an option to center it can help ensure that a normalization affects both upper and lower parts of the waveform.
* Drawing/sample touch ups - sometimes misalignments happen in the process of cutting and such, being able to interpolate points or just manually draw or move up and down sample points (while zoomed in for example). Being able to draw oneshot samples straight up from scratch could be a fun exercise too (something that people could do with by holding right mouse button in ProTracker/FastTracker 2/Milkytracker and also OpenMPT)

But yeah, I realize these might be more 'long-term' things, or may be out of scope, since one can always use an external sample editor; just some ideas I thought were useful. 

Also how do you feel about feature requests being moved to Discussions, as there's a section for Ideas there? Hate to spam you with tons of things.

**Comment by Dannode36** [comment]
I'll take a crack at implementing some of your additional features but the redo/undo history should probably be left up to @squiggythings from an architecture perspective.
