### ISSUE TITLE
Resampling mode for samples are not saved  (and some other things)

### ISSUE THREAD

**Issue by bryc** [squiggythings/WaveTracker#3]
I'm trying to use **Harsh (None)** for some low sample-rate drum samples, and when I reload the .WT, it resets to **Smooth (Linear)**.  So it doesn't seem like the setting is getting saved.

Not much else to say about that!

****

Also, not a bug but a suggestion: for very short drum samples, like tiny chiptune drums under 800 samples, when clicking on a .wav in the file browser, it automatically uses "Forward" loop point, which sounds very harsh and unpleasant on some samples - I think an option to set this to be "One Shot" by default would be useful.

**Comment by squiggythings** [comment]
Resample modes saving issue has been fixed. As for looping, I agree it is best to leave this off by default, and include a checkbox to loop the sample preview in the sample browser if the user wishes to hear them that way.
