### ISSUE TITLE
[BUG] Visualizer "draw in maximum resolution" is broken

### ISSUE THREAD

**Issue by blw043** [squiggythings/WaveTracker#32]
**Describe the bug**
The visualizer does not render when "draw in maximum resolution" is on. 
It renders correctly when option is off.

**To Reproduce**
1. Check "draw in maximum resolution" under Preferences > Visualizer
2. Open the visualizer.

**Expected behavior**
The visualizer should be rendered in high resolution as in Wavetracker 1.0.1.

**Desktop (please complete the following information):**
 - OS: Windows 11 v23H2, x86-64
 - Version: WaveTracker 1.0.2 64-bit

**Comment by squiggythings** [comment]
Just noticed this myself! It broke with changes to the rendering system made in 1.0.2. I'm going to upload a patch shortly that fixes this. Thanks for letting me know.
