### ISSUE TITLE
[Feature Request] support for a chromatic keyboard layout

### ISSUE THREAD

**Issue by idadeerz** [squiggythings/WaveTracker#33]
i'm extremely used to OpenMPT's keyboard layout, which is chromatic/linear as opposed to the piano-style layout a lot of trackers use. what this means is that every key row is one octave (or at least, as far as they get) starting with C, and every key to the right is +1 note. the home row has the main octave, the rows above and below it are +1 octave and -1 octave. the number keys function as octave switches, so if you press one of those it will tune the note to the corresponding octave. i find this layout a lot more efficient to work with as not a single key is wasted here, there's more notes, and if i miss a note/key i can just press the one to the left/right to fix it. a piano layout doesn't give me that muscle memory.

having keyboard remapping available in WaveTracker is great! however, it's fully designed around a two-octave keyboard, which is what the piano layout has. i've remapped these to the top and home rows of my keyboard, but the bottom row is unused now because there's only bindings available for two octaves :( ideally if there were more octaves to remap in the keyboard bindings that would fix my problem.

but i also wonder if it might be an option to implement a way to save key/note mappings separately? would be cool to include a set of default alternate mappings with the software, or have a way for users to exchange them in case anyone would like to try a different layout.

**Comment by squiggythings** [comment]
Two extra octaves (the 3rd and 4th above the base octave) of key bindings will be available in an upcoming update, they will be empty by default, but obviously can be rebound to allow a full chromatic keyboard layout. Also key bindings for setting the octave directly to 0-9 will be included.
