### ISSUE TITLE
[BUG] double click selects whole channel no matter where i click

### ISSUE THREAD

**Issue by idadeerz** [squiggythings/WaveTracker#34]
**Describe the bug**
i prefer using a mouse with a tracker. specifically, i like to enter notes by turning follow mode on and then alternating between clicking on a cell + entering a note. it's a very efficient way to enter notes in rapid succession aside from changing the step length.

one thing that complicates this in WaveTracker is that it seems like if i click my left mouse button too fast, it registers this as a double click, and instead of advancing the position of the cursor it just selects the whole channel. i have to kinda guess what the interval between a single click and a double click is and that's kinda tricky to do.

**To Reproduce**
1. open WaveTracker
2. make sure follow mode is on
3. click on a cell, then click on the one a few steps below it, this will now put this cell in the center because follow mode is on
4. repeat this to rapidly advance through all the cells.
5. if you click on the cells too fast, it'll instead just select the whole channel instead of advancing the position

**Expected behavior**
double clicking should only result in selecting the whole channel *if you are double clicking on the cursor/selected cell.* if you're not clicking on the cursor, it should just advance the cursor position as usual and not select anything.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 1.0.2

**Comment by squiggythings** [comment]
This would sometimes bother me as well in Famitracker. It will be changed in an upcoming update to only select all if you double click on the row that the cursor is on.
