### ISSUE TITLE
Generate waveform based on a math expression

### ISSUE THREAD

**Issue by darkhog** [squiggythings/WaveTracker#36]
It would be nice that if in addition to drawing a waveform ourselves, we could calculate it based on a math expression. Examples:

sin(t) would give a classic sinewave
wave(0)+wave(4)-wave(2) would add wave 0 and 4 together, then subtract wave 2 from it (using current wave's number there could lead to infinite loop and as such wouldn't be allowed)

Possibly even more fun stuff that I don't know would be possible. The idea came after playing around with LMMS Nightly Xpressive plugin that generates waveforms from equations.

**Comment by Dannode36** [comment]
Creating waveforms from math expressions is always a fun and interesting sound design element. My only experience with this is with the Fruity Formula Controller.
I'll make an attempt at writing a custom expression parser, possibly inspired by Fruity Formula Controller.
