### ISSUE TITLE
[Feature Request] sample offset/sample cue command

### ISSUE THREAD

**Issue by idadeerz** [squiggythings/WaveTracker#38]
i love that WaveTracker has sample instruments built-in, i feel like it really sets it apart from Famitracker and makes it more suited to the sample-based stuff i usually make in OpenMPT. but one thing that would make this even better is a sample offset command.

in the ProTracker/FTII command set (which Fami uses too i believe) this is command 9xx, though that one's already been taken in WaveTracker so i guess it'll have to be something else if this gets implemented.

what the sample offset command does is when paired with an instrument/note trigger, it offsets the sample start position by the amount specified in the effect value. so 901 would advance it by 256 samples, 910 by 4096 samples, etc. one use for this is chopping breaks; in OpenMPT's sample editor, you can hover over the waveform and find out the corresponding offset command for the section you are hovering over. so if you hover over the snare, it will tell you what offset command you need in order to play the snare. and from that you can chop breaks or other samples with several different hits in them and create drum patterns out of them.

Fami/WaveTracker are both very different from PT/FTII/OMPT in how their effects are on continuously until you turn them off; in the other trackers, effects are only active whenever there is a command. i'm not sure how this would work with sample offset. maybe the offset keeps getting applied to any new notes until 900 is triggered?

perhaps a more user-friendly implementation of sample offset would be how [Squarp Rample](https://squarp.net/rample/) handles sample slicing; basically it splits any sample into 8 or 16 different equal-length chunks, and the start position setting swaps between them. maybe there could be a sample offset command that goes from 900 to 915 (decimal, not hexadecimal) like that? being able to chop breaks and manipulate samples even more would be a great addition to the software!!

**Comment by bryc** [comment]
Would being able to set exact slice points in the sample instrument and triggering each index with an effect, not be a better idea than ProTracker sample offset effect, which may lack precision? Like how pretty much every modern sampler does it. Never really used the old ProTracker way personally, so I'm not sure what it offers over it.

Sometimes I just string my drum samples together in one wav file and cut them into regions in a sampler, so I definitely see value in this as a creative tool.

**Comment by squiggythings** [comment]
This feature is already in WaveTracker, it's the Yxx command which starts the sample a percentage of the way through. So Y50 will start halfway through the sample. But thanks for letting me know because I accidentally left this out of the effect list on the documentation, I will update it to match.
