### ISSUE TITLE
[BUG] Recent files crash the program

### ISSUE THREAD

**Issue by TimCherikov** [squiggythings/WaveTracker#39]
**Describe the bug**
When I hover the mouse over "Recent files", the program does not respond and closes.

**To Reproduce**
File -> Recent files

**Expected behavior**
My recent files ;(

**Desktop (please complete the following information):**
 - OS: Windows 11 22000.2538
 - Version: 1.0.1 - 1.0.3

**Additional context**
I've been writing music for an hour, and I accidentally looked at recent files. The music has been completely deleted. Please make an autosave every 5 minutes

**Comment by bryc** [comment]
I can confirm this bug, cyrillic characters in a recent path will crash app when the menu opens.
