### ISSUE TITLE
[BUG] The damifortune - precision dash.wtm sounds garbled

### ISSUE THREAD

**Issue by sandord** [squiggythings/WaveTracker#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:
 - Version: 

**Additional context**

**Comment by squiggythings** [comment]
Damifortune is a glitch artist, so stutters and warbles are intentional sound design choices. Just to be sure, is this how the module sounds for you?

https://github.com/user-attachments/assets/05bc5287-97dc-4df4-8470-c0ffc708c02f

**Comment by sandord** [comment]
Shoot, I didn't mean to actually post this, while writing I figured it might be stylistically intentional. Somehow I pressed submit anyway!

And yes, it sounds exactly like the wav you posted 👍
