### ISSUE TITLE
[Feature Request] button to rename instruments

### ISSUE THREAD

**Issue by Icondor15** [squiggythings/WaveTracker#43]
This is a very tiny thing, i think it'd be neat if you could open the 'rename instrument' window with a button :)

Love the tracker by the way, it has inspired me to make music again!

**Comment by Icondor15** [comment]
I meant a keyboard shortcut! sorry for the confusion heh

**Comment by squiggythings** [comment]
No worries! This will be included in the next patch with the default set to Ctrl+R
