### ISSUE TITLE
[BUG] Application fails to launch on windows 11

### ISSUE THREAD

**Issue by NapalmHammer** [squiggythings/WaveTracker#46]
**Describe the bug**
Application fails to open on Windows 11, no apparent reason.

**To Reproduce**
1. Extracted the application files from zip
2. Opened application , installed .NET8.0 via prompt
3. Spent some time creating and saving a track named the saved file "getting started.wtm"
4. Closed application

**Expected behavior**
Opening application via double click or right-click and open will launch the application.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version: 10.0.22631 Build 22631

**Additional context**
Checking in Windows Event Viewer, I see some information I think will be helpful .NET error logged:

> Application: WaveTracker.exe
> CoreCLR Version: 8.0.824.36612
> .NET Version: 8.0.8
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at WaveTracker.SaveLoad.ReadPath(String pathName, String defaultPath)
>    at WaveTracker.UI.SampleBrowser..ctor()
>    at WaveTracker.UI.SampleEditor..ctor(Int32 x, Int32 y, Element parent)
>    at WaveTracker.UI.InstrumentEditor..ctor()
>    at WaveTracker.App.Initialize()
>    at Microsoft.Xna.Framework.Game.DoInitialize()
>    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
>    at WaveTracker.Program.Main(String[] args)

**Comment by NapalmHammer** [comment]
Wanted to point out that after some looking at the source code and following the logic, I think I figured out what is causing the issue. 

In my user's AppData > Roaming > WaveTracker > Path folder, there is a file called sample.path. This file is empty. 

Based on the .NET error, I followed the source code to SampleBrowser.cs line that runs `SaveLoad.ReadPath()`. In SaveLoad.cs line 675 it runs this code `File.ReadAllLines(filepath)[0]` Which I think causes an "Index was outside the bounds of the array" exception since in my case the file is empty.

To test this, I simply added a file path to this sample.path file, and sure enough the application now opens for me. 

I may be wrong, but I wanted to share this in case it helps.

**Comment by squiggythings** [comment]
Thanks for letting me know. It will be fixed in the next patch, which I'll get rolled out as soon as I can. I did some more digging, and it might be helpful to know in the meantime that this crash is being caused specifically when the root path is selected in the sample editor at the time you close it.
