### ISSUE TITLE
[Feature Request] Noise generator?

### ISSUE THREAD

**Issue by brickblock369** [squiggythings/WaveTracker#47]
Could WaveTracker have a random noise generator? It would be useful for certain types of drums. I don't think there's anything like it in WaveTracker.

While yes, in the meantime we could randomly cycle through waves at a very high speed, but I think that would be too tedious.

**Comment by 0hStormy** [comment]
You can create very low resolution noise with the wavetables, but they have a tone to them. This would be a cool feature!

**Comment by Roxy-Pop** [comment]
Seconding that this would be a super fun feature! I'm currently importing a sample of white noise and pitching it up and down for my purposes, which has worked alright, but it would be nice to be able to access a noise generator mode on the normal wave instruments too, for more powerful drum creation.

**Comment by squiggythings** [comment]
In the next update will be a new 'noise instrument' alongside wave and sample instruments, it will have a basic noise generator that can be controlled with volume pitch and arpeggio envelopes. This should make it easier to play around with different white noise percussion without having to create them elsewhere and import them.
