### ISSUE TITLE
[Feature Request] In-app effects reference

### ISSUE THREAD

**Issue by cxong** [squiggythings/WaveTracker#61]
**Is your feature request related to a problem? Please describe.**
I would like to have a reference to the available effects within WaveTracker, so that I can quickly see the available effects and how to use them.

**Describe the solution you'd like**
Add a Help menu which includes an option to list the effects, which includes the same information available at https://wavetracker.org/documentation/effect-list/

**Describe alternatives you've considered**
Go to https://wavetracker.org/documentation/effect-list/ in a browser

**Additional context**
Having this information available quickly within the app will reduce friction when using effects. As an added bonus, this info can also be available offline when the user doesn't have internet access or the website is down. However, in the interim a menu option that simply opens a browser window to the online documentation is also a good incremental feature.

For reference, this is how bambootracker implements the same thing: 
![noah](https://github.com/user-attachments/assets/9863fd37-783b-4df8-bae7-aadd9404d85c)

**Comment by squiggythings** [comment]
A Help menu with links to documentation has been added to the and will be out in the next update, as well as a tooltip in the bottom information bar that displays what the current effect does whenever you edit an effect in the pattern editor.
