### ISSUE TITLE
[BUG] Recording noise instrument causes WaveTracker 1.1.1 to crash

### ISSUE THREAD

**Issue by dumenglume** [squiggythings/WaveTracker#62]
**Describe the bug**
WaveTracker crashes completely when attempting to record any noise instrument into any track. Wave and sample instruments function as normal.

**To Reproduce**
1. Create new noise instrument
2. Switch to record mode
3. Attempting any note using QWERTY keyboard into any channel results in crash

**Expected behavior**
To place the recorded note into the desired track

**Screenshots**
What it looks like right before placing a note:

![image](https://github.com/user-attachments/assets/1de9dda5-6d5f-40b6-8050-1e1aa2ac2748)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: Version 10.0.19045 Build 19045

**Comment by squiggythings** [comment]
I'm having trouble reproducing this, if anybody else is able to reproduce this please let me know.

https://github.com/user-attachments/assets/beeff523-cdf2-4491-9353-4e2108250336

**Comment by dumenglume** [comment]
That worked! Thank you for the quick response. Would have never guessed color palette being the cause but what you described makes sense.

Apologies if this is outside the scope of this thread but in the case of multiple feature requests, should they all be separate or lumped into one post?

**Comment by squiggythings** [comment]
Preferably separate! that way I can check each of them off individually if they are added or if others want to make a pull request.
