### ISSUE TITLE
[BUG] WaveTracker 1.1.1 crashes on Windows 10

### ISSUE THREAD

**Issue by defensem3ch** [squiggythings/WaveTracker#64]
**Describe the bug**
Opening WaveTracker results in a crash

**To Reproduce**
Double click on WaveTracker.exe

**Expected behavior**
Program doesn't open

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
I've tried building this in Visual Studio but get this error when trying to debug (screenshot attached)
![image](https://github.com/user-attachments/assets/4f49a94a-76a4-4a03-82e8-74bfc1fb001f)

**Comment by Dannode36** [comment]
Could you show the call stack for this exception please?

**Comment by Dannode36** [comment]
I've actually seen the same error when minimizing the application. I just never tried to track down what caused it :p

**Comment by squiggythings** [comment]
Thanks for letting me know, I will get a fix out as soon as I can. It's caused when a scrollbar has negative width and tries to position the scrollbar button

**Comment by squiggythings** [comment]
This is patched in 1.1.2

**Comment by defensem3ch** [comment]
thanks so much!!!
