### ISSUE TITLE
[BUG] WaveTracker closes / crashes shortly after minimizing

### ISSUE THREAD

**Issue by dumenglume** [squiggythings/WaveTracker#65]
**Describe the bug**
Anytime I minimize WaveTracker 1.1.1, it will close / crash a couple seconds later.

**To Reproduce**
1. Open WaveTracker
2. Minimize WaveTracker
3. A few seconds later, WaveTracker will close unexpectedly

**Expected behavior**
WaveTracker should remain open in the background and be able to be maximized again.

**Screenshots**
![image](https://github.com/user-attachments/assets/7cf9387a-366e-45e6-a5be-f1ea2eb205a2)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Version 10.0.19045 Build 19045

**Additional context**
Not sure if it's related, but the "WaveTracker quit unexpectedly last time." warning appears each time WaveTracker 1.1.1 is opened (see screenshot above)

**Comment by squiggythings** [comment]
This is due to the same issue as #64 , it is fixed in 1.1.2
