### ISSUE TITLE
[Feature Request] Frame Repeat Play mode

### ISSUE THREAD

**Issue by bryc** [squiggythings/WaveTracker#7]
Some trackers have a mode where it can play the selected frame on repeat.

It's useful I think and would come in super handy when tweaking waveforms / instruments while listening to a specific part in isolation, without it always switching over to the next frame, which may not use that instrument. 😄

**Comment by Ferdi265** [comment]
I second this. Famitracker has this on Alt+Enter, which is taken by play from cursor (but Shift+Enter is still free, which is what play from cursor is mapped to in Famitracker), and I used it all the time when tweaking instruments. Having to add a loop command at the end of the pattern each time you want to do this gets tedious after a while.

**Comment by squiggythings** [comment]
There have been quite a few people asking for this. A 'play and loop current pattern' feature will be added in the next patch.
